name: D

on: [push, pull_request]

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
    - name: 'Build & Test'
      run: dub test -b=unittest-cov
    - uses: codecov/codecov-action@v2
    - uses: dgellow/action-dscanner@v1
      with:
       # reviewdog config
       reporter: github-pr-review
       level: warning
